### ISSUE TITLE
Could not pass the bootloader verify.

### ISSUE THREAD

**Issue by sjllls** [sjllls/android_kernel_sony_sdm845#1]
Phone reported: 
Your device is corrupt ... and your device can't be trusted

无法通过启动验证

**Comment by sjllls** [comment]
@iovf 我在尝试制作基于官方驱动的los，但是现在内核出现了问题，无法通过bl的启动验证，你能帮我找一下原因吗，设备树已经上传，谢谢

**Comment by iovf** [comment]
这个我真是不太清楚，提个建议，你可以试试sony aosp内核 或者 原版内核 ，或者 我自己的内核。
