### ISSUE TITLE
Hide unlocked state seems no effect

### ISSUE THREAD

**Issue by gumibea** [sjllls/android_kernel_sony_sdm845#2]
.618 的 v1.0 与 v1.1 似乎隐藏并没有起作用，或者我理解错了功能？

**Comment by sjllls** [comment]
> .618 的 v1.0 与 v1.1 似乎隐藏并没有起作用，或者我理解错了功能？

难道你没有收到Sony推送的计算器更新吗？

**Comment by gumibea** [comment]
计算器确实没有收到

**Comment by sjllls** [comment]
> 计算器确实没有收到

测试后OTA功能是正常的，没有问题。
