### ISSUE TITLE
Xperia XZ2C/H8324 Touchscreen not working

### ISSUE THREAD

**Issue by KevinMX** [sjllls/android_kernel_sony_sdm845#3]
型号Xperia XZ2 Compact/H8324，618版本的固件，刷了eXistenZ Q，触摸屏不能用。
尝试过1.2和1.1 non-OC，都不行。
Device HW Info里面显示的型号是synaptics_tcm_i2c(i2c2-003c)。
可能是不同批次的屏幕/驱动芯片？

Touchscreen won't work on my Xperia XZ2 Compact/H8324(with eXistenZ Q)
Tried 1.2/1.1 non-OC, neither worked.
The touchscreen showsup in Device HW Info: synaptics_tcm_i2c(i2c2-003c)

**Comment by sjllls** [comment]
> 型号Xperia XZ2 Compact/H8324，618版本的固件，刷了eXistenZ Q，触摸屏不能用。
> 尝试过1.2和1.1 non-OC，都不行。
> Device HW Info里面显示的型号是synaptics_tcm_i2c(i2c2-003c)。
> 可能是不同批次的屏幕/驱动芯片？
> 
> Touchscreen won't work on my Xperia XZ2 Compact/H8324(with eXistenZ Q)
> Tried 1.2/1.1 non-OC, neither worked.
> The touchscreen showsup in Device HW Info: synaptics_tcm_i2c(i2c2-003c)

我现在不在官方系统下面，没法检查，有时间的话我会集成触摸驱动的，现在的工作重心在LineageOS上面。

**Comment by KevinMX** [comment]
看了一下你内核源码里面确实缺synaptics_tcm的驱动，但是今天我问了一下Martin，他说Sony原厂系统的固件是存在/vendor里面的……可能问题不在这？
需要其他协助的话随时回复:)

**Comment by sjllls** [comment]
> 看了一下你内核源码里面确实缺synaptics_tcm的驱动，但是今天我问了一下Martin，他说Sony原厂系统的固件是存在/vendor里面的……可能问题不在这？
> 需要其他协助的话随时回复:)

@KevinMX  触摸屏问题已修复, 麻烦上传xz2c最新的.2.1 boot.img.

**Comment by sjllls** [comment]
> 看了一下你内核源码里面确实缺synaptics_tcm的驱动，但是今天我问了一下Martin，他说Sony原厂系统的固件是存在/vendor里面的……可能问题不在这？
> 需要其他协助的话随时回复:)

触摸驱动已添加.
